services:
  meal-booking:
    image: bdzapps/meal-booking:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: meal-booking-app
